version: '3'
services:
  node-app:
    container_name: "express-node-app-prod-container"
    image: aniszariat/tresmerge-nodeapp-docker
    build:
      context: .
      # target: production
      args:
        - NODE_ENV=production
    ports:
      - "${PROD_MACHINE_PORT}:${PORT}"
    environment:
      - NODE_ENV=production
