version: '3'
services:
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - postgres
      # - mongo
  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     # ME_CONFIG_BASICAUTH_ENABLED: true
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis:
    image: redis
  nginx:
    container_name: "nginx"
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./templates:/etc/nginx/templates
    ports:
      - "8085:80"
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80
    depends_on:
      - node-app
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ROOT_USERNAME: root
      POSTGRES_INITDB_ROOT_PASSWORD: example

volumes:
  # mongo-db:
  postgres-db:
  
